In [99]:
#importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import sigmoid_kernel
import seaborn as sns
import matplotlib.pyplot as plt

In [100]:
data_cred=pd.read_csv("tmdb_5000_credits.csv") #importing the necessary csv files
data_mov=pd.read_csv("tmdb_5000_movies.csv")

In [101]:
data_mov.head(5) #exploring the movies data (using head())

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [102]:
data_cred.head(5) #exploring credits csv

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [103]:
#merging both data frames based on title and creating a new data frame "data"
data=pd.merge(data_mov,data_cred,on="title")

In [104]:
data.head() #exploring the new merged data

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [105]:
data.info() #checking for non-null

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [106]:
data=data.drop(columns=["movie_id","homepage","status","title","production_countries"])

In [107]:
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# a) Weighted hybrid technique
source: http://trailerpark.weebly.com/imdb-rating.html?source=post_page

# W=(R*v+C*m)/(v+m)
where:
* W=weighted rating 
* R=avg rating at the range (0-10) - "vote_average"
* v= no of votes - "vote_count"
* m= min no. of votes to be considered(here considering 75% of total votes) - "vote_count.quantile(75/100)"
* C=mean of vote across whole data - "vote_average.mean()"

In [108]:
R=data["vote_average"] #initializing the values for the respective
v=data["vote_count"]
C=data["vote_average"].mean()
m=data["vote_count"].quantile(0.75)

In [109]:
data["weighted_avg"]=(((R*v)+(C*m))/(v+m)).round(1) #creating a new column "weighted_avg" where the weighted average is stored

In [110]:
data.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew,weighted_avg
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.1
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.8
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.5
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1

In [111]:
data=data.sort_values("weighted_avg",ascending=0) #sorting the data frame with respect to"weighted_avg"

In [112]:
weighted_data=data[["original_title","weighted_avg","vote_average","vote_count","popularity"]] 
#selecting the necessary columns to be considered for weighted average

In [113]:
weighted_data.head(20) #this dataframe is not considering popularity of the movie so it is biased on weighted average

,original_title,weighted_avg,vote_average,vote_count,popularity
1887,The Shawshank Redemption,8.3,8.5,8205,136.747729
3237,Pulp Fiction,8.1,8.3,8428,121.463076
662,Fight Club,8.1,8.3,9413,146.757391
3342,The Godfather,8.1,8.4,5893,143.659698
65,The Dark Knight,8.1,8.2,12002,187.322927
809,Forrest Gump,8.0,8.2,7927,138.133331
3872,Whiplash,8.0,8.3,4254,192.528841
95,Interstellar,8.0,8.1,10867,724.247784
96,Inception,8.0,8.1,13752,167.583710
1824,Schindler's List,8.0,8.3,4329,104.469351
1996,The Empire Strikes Back,8.0,8.2,5879,78.517830
2300,千と千尋の神隠し,7.9,8.3,3840,118.968562
690,The Green Mile,7.9,8.2,4048,103.698022
329,The Lord of the Rings: The Return of the King,7.9,8.1,8064,123.630332
2737,The Godfather: Part II,7.9,8.3,3338,105.792936
262,The Lord of the Rings: The Fellowship of the Ring,7.9,8.0,8705,138.049577
2917,Star Wars,7.9,8.1,6624,126.393695
1559,Se7en,7.9,8.1,5765,79.579532
2097,The Silence of the Lambs,7.8,8.1,4443,18.174804
2528,The Imitation Game,7.8,8.0,5723,145.364591

# If we need to consider popularity we shall use 1/2 of weighted avg and 1/2 of popularity to give an unbiased output

In [114]:
scl=MinMaxScaler() #since both weighted_avg and popularity are of different ranges we are using min ax scaler 
data_df=scl.fit_transform(weighted_data[["weighted_avg","popularity"]])
data_norm=pd.DataFrame(data_df,columns=["weighted_avg","popularity"])
data_norm #normalized data

      weighted_avg  popularity
0         1.000000    0.156179
1         0.942857    0.138723
2         0.942857    0.167611
3         0.942857    0.164074
4         0.942857    0.213941
...            ...         ...
4804      0.085714    0.036858
4805      0.028571    0.024758
4806      0.028571    0.027595
4807      0.000000    0.057189
4808      0.000000    0.043544

[4809 rows x 2 columns]

In [115]:
data[["Norm_W_Avg","Norm_Popularity"]]=data_norm #appending it to the cleaned data

In [132]:
data.head(10)

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,...,spoken_languages,tagline,vote_average,vote_count,cast,crew,weighted_avg,Norm_W_Avg,Norm_Popularity,rating
1887,25000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",278,"[{""id"": 378, ""name"": ""prison""}, {""id"": 417, ""n...",en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",1994-09-23,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Fear can hold you prisoner. Hope can set you f...,8.5,8205,"[{""cast_id"": 3, ""character"": ""Andy Dufresne"", ...","[{""credit_id"": ""52fe4231c3a36847f800b153"", ""de...",8.3,0.371429,0.001187,0.186308
3237,8000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",680,"[{""id"": 396, ""name"": ""transporter""}, {""id"": 14...",en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",1994-10-08,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Just because you are a character doesn't mean ...,8.3,8428,"[{""cast_id"": 2, ""character"": ""Vincent Vega"", ""...","[{""credit_id"": ""52fe4269c3a36847f801caa3"", ""de...",8.1,0.371429,0.026858,0.199143
662,63000000,"[{""id"": 18, ""name"": ""Drama""}]",550,"[{""id"": 825, ""name"": ""support group""}, {""id"": ...",en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",1999-10-15,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Mischief. Mayhem. Soap.,8.3,9413,"[{""cast_id"": 4, ""character"": ""The Narrator"", ""...","[{""credit_id"": ""55731b8192514111610027d7"", ""de...",8.1,0.485714,0.043420,0.264567
3342,6000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",238,"[{""id"": 131, ""name"": ""italy""}, {""id"": 699, ""na...",en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",1972-03-14,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",An offer you can't refuse.,8.4,5893,"[{""cast_id"": 5, ""character"": ""Don Vito Corleon...","[{""credit_id"": ""52fe422bc3a36847f80093c9"", ""de...",8.1,0.371429,0.029215,0.200322
65,185000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",155,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight,Batman raises the stakes in his war on crime. ...,187.322927,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",2008-07-16,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Why So Serious?,8.2,12002,"[{""cast_id"": 35, ""character"": ""Bruce Wayne"", ""...","[{""credit_id"": ""55a0eb4a925141296b0010f8"", ""de...",8.1,0.771429,0.128272,0.449851
809,55000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",13,"[{""id"": 422, ""name"": ""vietnam veteran""}, {""id""...",en,Forrest Gump,A man with a low IQ has accomplished great thi...,138.133331,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",1994-07-06,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",8.2,7927,"[{""cast_id"": 7, ""character"": ""Forrest Gump"", ""...","[{""credit_id"": ""52fe420ec3a36847f800076b"", ""de...",8.0,0.485714,0.035481,0.260598
3872,3300000,"[{""id"": 18, ""name"": ""Drama""}]",244786,"[{""id"": 1416, ""name"": ""jazz""}, {""id"": 1523, ""n...",en,Whiplash,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",2014-10-10,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The road to greatness can take you to the edge.,8.3,4254,"[{""cast_id"": 5, ""character"": ""Andrew Neimann"",...","[{""credit_id"": ""54d5356ec3a3683ba0000039"", ""de...",8.0,0.342857,0.010918,0.176888
95,165000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",157336,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Interstellar,Interstellar chronicles the adventures of a gr...,724.247784,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",2014-11-05,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Mankind was born on Earth. It was never meant ...,8.1,10867,"[{""cast_id"": 9, ""character"": ""Joseph Cooper"", ...","[{""credit_id"": ""52fe4bbf9251416c910e4801"", ""de...",8.0,0.742857,0.084925,0.413891
96,160000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",27205,"[{""id"": 1014, ""name"": ""loss of lover""}, {""id"":...",en,Inception,"Cobb, a skilled thief who commits corporate es...",167.583710,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2010-07-14,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Your mind is the scene of the crime.,8.1,13752,"[{""cast_id"": 1, ""character"": ""Dom Cobb"", ""cred...","[{""credit_id"": ""56e8462cc3a368408400354c"", ""de...",8.0,0.742857,0.049617,0.396237
1824,22000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",424,"[{""id"": 1382, ""name"": ""factory""}, {""id"": 1631,...",en,Schindler's List,The true story of how businessman Oskar Schind...,104.469351,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",1993-11-29,...,"[{""iso_639_1"": ""de"", ""name"": ""Deutsch""}, {""iso...","Whoever saves one life, saves the world entire.",8.3,4329,"[{""cast_id"": 14, ""character"": ""Oskar Schindler...","[{""credit_id"": ""52fe4242c3a36847f8010303"", ""de...",8.0,0.400000,0.003759,0.201880

In [143]:
data["rating"]=data["Norm_W_Avg"]*0.5 + data["Norm_Popularity"]*0.5
dt1=data.sort_values("rating",ascending=False)

In [144]:
dt1=dt1[["original_title","rating","Norm_W_Avg","Norm_Popularity","vote_average","vote_count"]]

In [145]:
dt1.head(10)

,original_title,rating,Norm_W_Avg,Norm_Popularity,vote_average,vote_count
7,Avengers: Age of Ultron,0.870724,0.914286,0.827162,7.3,6767
982,Free State of Jones,0.728571,0.457143,1.000000,6.6,428
22,The Hobbit: The Desolation of Smaug,0.703302,0.857143,0.549462,7.6,4524
121,Night at the Museum: Battle of the Smithsonian,0.650988,0.714286,0.587690,5.9,1971
4,John Carter,0.578399,0.942857,0.213941,6.1,2124
0,Avatar,0.578090,1.000000,0.156179,7.2,11800
216,Life of Pi,0.576566,0.657143,0.495989,7.2,5797
6,Tangled,0.567086,0.914286,0.219887,7.4,3330
2,Spectre,0.555234,0.942857,0.167611,6.3,4466
3,The Dark Knight Rises,0.553465,0.942857,0.164074,7.6,9106

# b)Content Based Recommendation

In [68]:
data.overview #considering overview ad using NLP since its totally text based

1887    Framed in the 1940s for the double murder of h...
3237    A burger-loving hit man, his philosophical par...
662     A ticking-time-bomb insomniac and a slippery s...
3342    Spanning the years 1945 to 1955, a chronicle o...
65      Batman raises the stakes in his war on crime. ...
                              ...
303     Liquidated after discovering a corporate consp...
1658    The young warrior Son Goku sets out on a quest...
3753    A recently cheated on married woman falls for ...
210     Along with crime-fighting partner Robin and ne...
242     Four young outsiders teleport to a dangerous u...
Name: overview, Length: 4809, dtype: object

In [69]:
data.genres #we can also use genre but the accuracy of recommendation will be drastically reduced due to the lack of variations

1887    [{"id": 18, "name": "Drama"}, {"id": 80, "name...
3237    [{"id": 53, "name": "Thriller"}, {"id": 80, "n...
662                         [{"id": 18, "name": "Drama"}]
3342    [{"id": 18, "name": "Drama"}, {"id": 80, "name...
65      [{"id": 18, "name": "Drama"}, {"id": 28, "name...
                              ...
303     [{"id": 28, "name": "Action"}, {"id": 80, "nam...
1658    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3753                     [{"id": 53, "name": "Thriller"}]
210     [{"id": 28, "name": "Action"}, {"id": 80, "nam...
242     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, Length: 4809, dtype: object

In [70]:
TF=TfidfVectorizer(stop_words="english", #removesfiller words in english sucha s "the,a,and,etc.."
                   min_df=3, #removes terms that appear less than 3 times in our document
                   analyzer="word",#the feature should be made of word n-grams
                   token_pattern=r"\w{1,}",
                   ngram_range=(1,4),#the range of n-values for different n-grams to be extracted
                   strip_accents="unicode")#removes the accents since differnt accents may confuse the machine
data["overview"]=data["overview"].fillna('')

In [71]:
TF_mat=TF.fit_transform(data["overview"]) #fitting the values to form a matrix

In [147]:
TF_mat.shape #this matrix includes the vectorized form of words in overview

(4809, 10458)

In [148]:
sig=sigmoid_kernel(TF_mat,TF_mat)

In [74]:
sig

array([[0.76163431, 0.76159416, 0.76159448, ..., 0.76159416, 0.76159443,
        0.7615953 ],
       [0.76159416, 0.76163431, 0.76159471, ..., 0.76159481, 0.76159602,
        0.76159416],
       [0.76159448, 0.76159471, 0.76163431, ..., 0.76159416, 0.76159444,
        0.76159732],
       ...,
       [0.76159416, 0.76159481, 0.76159416, ..., 0.76163431, 0.76159416,
        0.76159561],
       [0.76159443, 0.76159602, 0.76159444, ..., 0.76159416, 0.76163431,
        0.76159446],
       [0.7615953 , 0.76159416, 0.76159732, ..., 0.76159561, 0.76159446,
        0.76163431]])

In [149]:
indx=pd.Series(data.index,index=data["original_title"]) #indexing the titles

In [153]:
indx.drop_duplicates() #drops duplicate values

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4804
Newlyweds                                   4805
Signed, Sealed, Delivered                   4806
Shanghai Calling                            4807
My Date with Drew                           4808
Length: 4809, dtype: int64

In [155]:
indx=indx.sort_values(ascending=True) #sorting the index values

In [156]:
indx

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4804
Newlyweds                                   4805
Signed, Sealed, Delivered                   4806
Shanghai Calling                            4807
My Date with Drew                           4808
Length: 4809, dtype: int64

In [157]:
def recc(title,sig=sig): #method for implementing recommendation
    print("Here's a list of recommended movies related to",x)
    ix=indx[title]
    sig_scr=list(enumerate(sig[ix]))
    sig_scr=sig_scr[1:16]
    mov_indx=[i[0] for i in sig_scr]
    return data["original_title"].iloc[mov_indx]

In [161]:
print("Enter any movie title:")
x=input()
recc(x)

Enter any movie title:
Inception
Here's a list of recommended movies related to Inception

3237                                         Pulp Fiction
662                                            Fight Club
3342                                        The Godfather
65                                        The Dark Knight
809                                          Forrest Gump
3872                                             Whiplash
95                                           Interstellar
96                                              Inception
1824                                     Schindler's List
1996                              The Empire Strikes Back
2300                                             千と千尋の神隠し
690                                        The Green Mile
329         The Lord of the Rings: The Return of the King
2737                               The Godfather: Part II
262     The Lord of the Rings: The Fellowship of the Ring
Name: original_title, dtype: object

# *** THE END ***